import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class RehabnowAppBar extends AppBar {
  RehabnowAppBar({
    List<Widget> actions,
    IconThemeData actionsIconTheme,
    bool automaticallyImplyLeading,
    Color backgroundColor,
    bool backwardsCompatibility,
    PreferredSizeWidget bottom,
    double bottomOpacity,
    Brightness brightness = Brightness.dark,
    bool centerTitle = true,
    double elevation,
    bool excludeHeaderSemantics,
    Widget flexibleSpace,
    Color foregroundColor,
    IconThemeData iconTheme,
    Key key,
    Widget leading,
    double leadingWidth,
    bool primary,
    Color shadowColor,
    ShapeBorder shape,
    SystemUiOverlayStyle systemOverlayStyle,
    TextTheme textTheme,
    String title,
    double titleSpacing,
    TextStyle titleTextStyle,
    double toolbarHeight,
    double toolbarOpacity,
    TextStyle toolbarTextStyle,
  }) : super(
          actions: actions,
          // actionsIconTheme: actionsIconTheme,
          // automaticallyImplyLeading: automaticallyImplyLeading,
          // backgroundColor: backgroundColor,
          // backwardsCompatibility: backwardsCompatibility,
          // bottom: bottom,
          // bottomOpacity: bottomOpacity,
          brightness: brightness,
          centerTitle: centerTitle,
          // elevation: elevation,
          // excludeHeaderSemantics: excludeHeaderSemantics,
          // flexibleSpace: flexibleSpace,
          // foregroundColor: foregroundColor,
          // iconTheme: iconTheme,
          // key: key,
          // leading: leading,
          // leadingWidth: leadingWidth,
          // primary: primary,
          // shadowColor: shadowColor,
          // shape: shape,
          // systemOverlayStyle: systemOverlayStyle,
          // textTheme: textTheme,
          title: Text(title),
          // titleSpacing: titleSpacing,
          // titleTextStyle: titleTextStyle,
          // toolbarHeight: toolbarHeight,
          // toolbarOpacity: toolbarOpacity,
          // toolbarTextStyle: toolbarTextStyle,
        );
}
