import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class RehabnowAppBar extends AppBar {
  RehabnowAppBar({
    required List<Widget> actions,
    required IconThemeData actionsIconTheme,
    required bool automaticallyImplyLeading,
    required Color backgroundColor,
    required bool backwardsCompatibility,
    required PreferredSizeWidget bottom,
    required double bottomOpacity,
    Brightness brightness = Brightness.dark,
    bool centerTitle = true,
    required double elevation,
    required bool excludeHeaderSemantics,
    required Widget flexibleSpace,
    required Color foregroundColor,
    required IconThemeData iconTheme,
    required Key key,
    required Widget leading,
    required double leadingWidth,
    required bool primary,
    required Color shadowColor,
    required ShapeBorder shape,
    required SystemUiOverlayStyle systemOverlayStyle,
    required TextTheme textTheme,
    required String title,
    required double titleSpacing,
    required TextStyle titleTextStyle,
    required double toolbarHeight,
    required double toolbarOpacity,
    required TextStyle toolbarTextStyle,
  }) : super(
          actions: actions,
          // actionsIconTheme: actionsIconTheme,
          // automaticallyImplyLeading: automaticallyImplyLeading,
          // backgroundColor: backgroundColor,
          // backwardsCompatibility: backwardsCompatibility,
          // bottom: bottom,
          // bottomOpacity: bottomOpacity,
          brightness: brightness,
          centerTitle: centerTitle,
          // elevation: elevation,
          // excludeHeaderSemantics: excludeHeaderSemantics,
          // flexibleSpace: flexibleSpace,
          // foregroundColor: foregroundColor,
          // iconTheme: iconTheme,
          // key: key,
          // leading: leading,
          // leadingWidth: leadingWidth,
          // primary: primary,
          // shadowColor: shadowColor,
          // shape: shape,
          // systemOverlayStyle: systemOverlayStyle,
          // textTheme: textTheme,
          title: Text(title),
          // titleSpacing: titleSpacing,
          // titleTextStyle: titleTextStyle,
          // toolbarHeight: toolbarHeight,
          // toolbarOpacity: toolbarOpacity,
          // toolbarTextStyle: toolbarTextStyle,
        );
}
